import type { Insumo, Producto, Proveedor, Usuario } from './types'

export const PROVEEDORES: Proveedor[] = [
  {
    id: 'p1',
    nombre: 'Molino La Espiga',
    insumo: 'Masa de maíz nixtamalizada',
    contacto: '55 1234 5678',
    correo: 'pedidos@laespiga.mx',
    direccion: 'Calz. de los Molinos 88, Iztapalapa',
    proximaEntrega: '26 ago',
    estado: 'activo',
  },
  {
    id: 'p2',
    nombre: 'Aceites del Bajío',
    insumo: 'Aceite vegetal',
    contacto: '55 2345 6789',
    correo: 'ventas@aceitesdelbajio.mx',
    direccion: 'Carr. Celaya km 12, Celaya',
    proximaEntrega: '29 ago',
    estado: 'activo',
  },
  {
    id: 'p3',
    nombre: 'Empaques Monarca',
    insumo: 'Bolsas paquete chico, mediano y grande',
    contacto: '55 3456 7890',
    correo: 'contacto@empaquesmonarca.mx',
    direccion: 'Parque Industrial Norte, nave 6',
    proximaEntrega: '27 ago',
    estado: 'activo',
    urgente: true,
  },
  {
    id: 'p4',
    nombre: 'Cartonera del Centro',
    insumo: 'Cajas paquete familiar',
    contacto: '55 4567 8901',
    correo: 'ventas@cartoneradelcentro.mx',
    direccion: 'Eje 3 Oriente 450, Centro',
    proximaEntrega: '3 sep',
    estado: 'activo',
  },
  {
    id: 'p5',
    nombre: 'Etiquetas Rex',
    insumo: 'Etiquetas de sello',
    contacto: '55 5678 9012',
    correo: 'hola@etiquetasrex.mx',
    direccion: 'Av. Insurgentes Sur 1900, local 4',
    proximaEntrega: '—',
    estado: 'inactivo',
  },
]

export const INSUMOS: Insumo[] = [
  { id: 'i1', nombre: 'Masa de maíz nixtamalizada', cantidad: 18, unidad: 'kg', minimo: 25, proveedorId: 'p1' },
  { id: 'i2', nombre: 'Aceite vegetal', cantidad: 40, unidad: 'L', minimo: 20, proveedorId: 'p2' },
  { id: 'i3', nombre: 'Bolsas paquete chico', cantidad: 120, unidad: 'pzas', minimo: 100, proveedorId: 'p3' },
  { id: 'i4', nombre: 'Bolsas paquete mediano', cantidad: 60, unidad: 'pzas', minimo: 80, proveedorId: 'p3' },
  { id: 'i5', nombre: 'Bolsas paquete grande', cantidad: 0, unidad: 'pzas', minimo: 50, proveedorId: 'p3' },
  { id: 'i6', nombre: 'Cajas paquete familiar', cantidad: 35, unidad: 'pzas', minimo: 20, proveedorId: 'p4' },
  { id: 'i7', nombre: 'Etiquetas de sello', cantidad: 500, unidad: 'pzas', minimo: 200, proveedorId: 'p5' },
]

export const PRODUCTOS: Producto[] = [
  { id: 'pr1', nombre: 'Paquete chico (10 pzas)', precio: 25, cantidad: 340, minimo: 150 },
  { id: 'pr2', nombre: 'Paquete mediano (20 pzas)', precio: 45, cantidad: 210, minimo: 150 },
  { id: 'pr3', nombre: 'Paquete grande (50 pzas)', precio: 100, cantidad: 22, minimo: 60 },
  { id: 'pr4', nombre: 'Paquete familiar (100 pzas)', precio: 180, cantidad: 18, minimo: 15 },
]

export const USUARIOS: Usuario[] = [
  {
    id: 'u1',
    nombre: 'Ana Ibarra',
    usuario: 'ana.ibarra',
    correo: 'ana.ibarra@ositostadas.mx',
    telefono: '55 1122 3344',
    rol: 'admin',
    fechaIngreso: '3 ene 2023',
    estado: 'activo',
  },
  {
    id: 'u2',
    nombre: 'María Duarte',
    usuario: 'maria.duarte',
    correo: 'maria.duarte@ositostadas.mx',
    telefono: '55 2233 4455',
    rol: 'vendedor',
    fechaIngreso: '14 jun 2024',
    estado: 'activo',
  },
  {
    id: 'u3',
    nombre: 'Luis Peña',
    usuario: 'luis.pena',
    correo: 'luis.pena@ositostadas.mx',
    telefono: '55 3344 5566',
    rol: 'vendedor',
    fechaIngreso: '2 sep 2024',
    estado: 'activo',
  },
  {
    id: 'u4',
    nombre: 'Rosa Elizalde',
    usuario: 'rosa.elizalde',
    correo: 'rosa.elizalde@ositostadas.mx',
    telefono: '55 4455 6677',
    rol: 'vendedor',
    fechaIngreso: '20 ene 2025',
    estado: 'activo',
  },
  {
    id: 'u5',
    nombre: 'Iván Cortés',
    usuario: 'ivan.cortes',
    correo: 'ivan.cortes@ositostadas.mx',
    telefono: '55 5566 7788',
    rol: 'vendedor',
    fechaIngreso: '11 mar 2025',
    estado: 'inactivo',
  },
]
